# Generated by Django 6.0.4 on 2026-04-17 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_latest",
        ),
    ]
