# Generated by Django 6.0.4 on 2026-04-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_latest",
            field=models.BooleanField(default=False),
        ),
    ]
